spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_demo
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
      # 连接池允许的最大连接数
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}

# mybatis的mapper书写路径
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    # 日志实现类
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    default-statement-timeout: ${MYBATIS_DEFAULT_STATEMENT_TIMEOUT:120}
    call-setters-on-nulls: true


logging:
  level:
    # 配置目录下的日志输出级别
    org.apache.ibatis: ${LOG_LEVEL:debug}
    com.example.springbootdemo: ${LOG_LEVEL:debug}
  file:
    # 配置日志输出文件的路径及文件名
    name: C:\Users\Summer\Desktop\springboot_demo.txt


